### ISSUE TITLE
Can you build a purple-skypeweb rpm?

### ISSUE THREAD

**Issue by 0312birdzhang** [Thaodan/haze-acounts-extensions-skypeweb#2]
I know it's skype4pidgin/skypeweb , but i build failed. <code>fatal error: glib.h: No such file or directory</code>

**Comment by Thaodan** [comment]
wrong buggtacker.... , I did. 
https://build.merproject.org/package/show/home:Thaodan/purple-skypeweb

**Comment by 0312birdzhang** [comment]
Thank you!
