### ISSUE TITLE
No compilation instructions

### ISSUE THREAD

**Issue by rodneyrod** [Thaodan/haze-acounts-extensions-skypeweb#3]
I run a non-RPM based distro, and I'm a bit lost on how to get this to compile so I can use it.

**Comment by Thaodan** [comment]
The plugin is only for Sailfish, there's  no sailfish without  rpm.

**Comment by rodneyrod** [comment]
Ahh, any chance of porting this so desktop Telepathy clients can use this too?
I'm unfamiliar with how everything works, and QML for that matter, therefore I'm unable to do it myself.

**Comment by rodneyrod** [comment]
@Thaodan What would it take to port this to desktop Telepathy?
jolla-settings-accounts isn't a dependency that can be used on desktop distributions and I knew several people who would want something like this for Telepathy proper.

**Comment by Thaodan** [comment]
I made a ui to create a skypeweb account for telepathy kde, so porting isn't needed.
